Repository bowe99/Smart-Home-Simulator, pull requests merged in 2020-12, with the labels that each got.

#74 #50 blocked windows functionality
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/Window.java
  src/com/simulator/view/Dashboard.fxml
Labels: Delivery-3, Functional req

#75 #45 #46 Implemented Zones feature and modifying the temperatures for the zone
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/model/Room.java
  src/com/simulator/model/Zone.java
  src/com/simulator/view/Dashboard.fxml
Labels: Delivery-3, Functional req

#81 Bug/issue#80/house layout bug
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/view/Dashboard.fxml
  src/com/simulator/view/lightOff.png
  src/com/simulator/view/people.jpg
Labels: Delivery-3

#82 #76 Rooms that are overwritten can now be added to zones
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/model/House.java
  src/com/simulator/model/Room.java
  src/com/simulator/model/Zone.java
Labels: Delivery-3, bug

#86 #54 junit&#53 javadocs
  src/com/simulator/controller/Logger.java
  src/com/simulator/controller/RoomControlsController.java
  src/com/simulator/controller/SimulationParameterController.java
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/model/House.java
  src/com/simulator/model/Permission.java
  src/com/simulator/model/Profile.java
  src/com/simulator/model/Room.java
  src/com/simulator/model/SecurityModule.java
  src/com/simulator/model/Sensor.java
  src/com/simulator/model/SimulationObserver.java
  src/com/simulator/model/SimulationParameters.java
  src/com/simulator/model/Temperature.java
  src/com/simulator/model/Time.java
  src/com/simulator/model/Window.java
  src/com/simulator/model/Zone.java
  tests/com/simulator/Delivery2/ContextOfTheSimulationTest.java
  tests/com/simulator/Delivery2/SimulationParametersTest.java
  tests/com/simulator/Delivery2/SmartHomeCoreFunctionalityModuleTest.java
  tests/com/simulator/Delivery2/SmartHomeDashboardTest.java
  tests/com/simulator/Delivery2/SmartHomeSecurityModuleTest.java
  tests/com/simulator/Delivery3/AcceptDesiredTempForEachTime.java
  tests/com/simulator/Delivery3/ChangeTempWhenInAwayMode.java
  tests/com/simulator/Delivery3/CreateZones.java
  tests/com/simulator/Delivery3/DisplayCurrentTemp.java
  tests/com/simulator/Delivery3/MonitorIndoorAndOutdoorTemp.java
  tests/com/simulator/Delivery3/OpenCloseWindowsWhenBlocked.java
  tests/com/simulator/Delivery3/RefactoringTest.java
  tests/com/simulator/Delivery3/SendAlertIfUnualTemp.java
  tests/com/simulator/Delivery3/ShutDownACOpenWindows.java
Labels: Delivery-3

#87 Feat/issue#62/showing temperature icons
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/view/Dashboard.fxml
  src/com/simulator/view/ac.png
  src/com/simulator/view/heater.png
Labels: Delivery-3

#89 Bug(Issue#6):Fix Multiple Parameter Editor's
  src/com/simulator/controller/SmartHomeSimulatorController.java
Labels: Delivery-3

#83 56 add exception handling
  src/com/simulator/controller/RoomControlsController.java
  src/com/simulator/controller/SimulationParameterController.java
  src/com/simulator/controller/SmartHomeSimulator.java
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/model/House.java
  src/com/simulator/model/HouseLoadException.java
Labels: Delivery-3

#88 #51 allow user to enter away mode temperature preferences for summer and winter
  src/com/simulator/controller/SmartHomeSimulatorController.java
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/view/Dashboard.fxml
Labels: Delivery-3, Functional req

#90 feat(Issue#61):Windows on Away Mode
  src/com/simulator/model/HeatingModule.java
  src/com/simulator/model/SecurityModule.java
  tests/com/simulator/Delivery2/SmartHomeCoreFunctionalityModuleTest.java
  tests/com/simulator/Delivery2/SmartHomeSecurityModuleTest.java
  tests/com/simulator/Delivery3/AcceptDesiredTempForEachTime.java
  tests/com/simulator/Delivery3/ChangeTempWhenInAwayMode.java
  tests/com/simulator/Delivery3/CreateZones.java
  tests/com/simulator/Delivery3/DisplayCurrentTemp.java
  tests/com/simulator/Delivery3/MonitorIndoorAndOutdoorTemp.java
  tests/com/simulator/Delivery3/OpenCloseWindowsWhenBlocked.java
  tests/com/simulator/Delivery3/SendAlertIfUnualTemp.java
  tests/com/simulator/Delivery3/ShutDownACOpenWindows.java
Labels: Delivery-3

#95 feat(Issue#85):Enhancing permissions
  src/com/simulator/model/HeatingModule.java
Labels: Delivery-3
